### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by theemack** [Raf-sns/Placido-Shop#2]
Love your write up on your software and its purpose...attempting to install and eager to see its effectiveness - followed all your directives but having issues bringing up the ADMIN as it only works on php.7.3 - up to php.8.1 results in a blank screen.

Does this app have to be placed in the root of the public folder itself or a directory?

![screenshot-loa-2022 12 12-17_33_33](https://user-images.githubusercontent.com/7733293/207128962-85a6eaa1-eeb7-4235-9288-ec5efa0ee396.png)

**Comment by Raf-sns** [comment]
Hi,
wow! your card is amazing...
You must have this:

-> What browser are you on?
-> Do you see any errors in the browser console?
-> I tested the appication on PHP 7.5 and 8.1
I develop the application on PHP 8.1

- Thank you for the feedback,
I will try to resolve this with you.
![Screenshot_12-12-2022_21-01-17](https://user-images.githubusercontent.com/36576486/207144016-9366f452-cedc-477b-a6b2-899e67542b5e.png)

**Comment by Raf-sns** [comment]
Mmm...
Did you install manually?
-> in this case you must edit the API/api.json file with the correct domain name on the "HOST" key
`"HOST": "my_personal_host.com",`
Also, the application requires the https protocol, it is preferable to test it on an online server, on a temporary subdomain for example

**Comment by theemack** [comment]
Raf-sns - thanks for your prompt response, deeply appreciated.

Using Linux and running Chrome and Firefox browsers and a shared web host, seems it does not install under a directory in the root - despite the required ssl in place. Created a sub-domain and it installed without issues after having seen your msg, now to install it directly in the root and support you by getting the license.

Just a few minors missing - having variations in the product such as "size  - colour - material" - the little critical options to making a purchase on a product. Any possibilities to add those two bits of code?

I've also noticed that an image shot from a mobile device right way up of-course appears anti-clockwise not sure if this is to do with your app?!

**Comment by Raf-sns** [comment]
Hi,
sorry i am sick today ...

-> - having variations in the product such as "size - colour - material"

Yes, as [mentioned here](https://placido-shop.com/about-us.html), I had to make choices and I had to make them alone.
In some cases it is interesting to offer options with the product but in others it would add complexity to adding a product.

I have just sold a version and I am asked to set up shipping costs but the customer does not know how to tell me what rules he wants to apply here and from what amount we must offer the shipping costs, I am thinking about this strategy.

Of course it is possible to modify everything or to adapt the application so that it corresponds to your needs.

In this case the most important thing is to take out the files you modify from the update, this is done in "Update", "Customize the update" enter here the full path of the file ex. : `ADMIN/PHP/products.php`
or `ADMIN/PHP` to exclude all .php files from the update.

For general operation (I need to finish the documentation),
The administration and the front work in the same way:

- The index.php file loads Mustache, the template engine, then it loads the PHP classes from the API folder and all the classes from the PHP folder (front or backend).
- The `api::init_settings();` takes data from the API/api.json file and turns it into constants for the whole application.
- `tr::init_tr('front/back');` loads the translation (this is specified in the api.json file)
- `api::init_modules( $context='front/back' );` load what there is load modules, so you can completely override the program from a module, because it comes before any other function.
- Finally, `control::start();` is called at the end of index.php, 
- the PHP/control.php file is the point of passage for all requests, only 'GET' and 'POST' are authorized.

The PHP/control.php file examines requests and either adjusts parameters before calling `program::get_home_page();` , or it receives a 'POST' request and it calls the function which corresponds to its "set" key.

In a PHP context of static public classes, all classes and their methods are accessible by all other classes.

To finish the explanation, take a simple connection to the application the logic follows the following path:
index.php -> PHP/control.php ( `control::start()` -> `control::router()` ), 
the router finds the request 'GET' == '/' , 
it calls PHP/program.php -> `program::get_home_page();`

The `get_home_page()` function constructs an array ($ARR) of nested arrays with all the application data (products, pagination, featured products, etc.) then we give this array to Mustache which uses it to fill in the {{...}} with the data from the global array.

-> The data is cached in a session, then we echo the html rendered by Mustache.

-> The site loads for the client and the javascript (JS/api_loader.js) immediately makes the same request, except that there `program::get_home_page();` returns the data cached by the previous session, in .json format.

-> When the server responds, the jQuery object is extended by an object '`$.o`' (o not zero) which contains all the data of the application in the form of an object.
This allows us to do 'Mustache' on the client side and manage a lot of things on the client side.

Keep in mind that:
- All PHP classes are named after their ex. the program class is in the PHP/program.php file
- At any time from the javascript console you can enter `$.o` to see the state of the global object of the application (it's useful for debugging).

-> When 'POST' requests are made, by AJAX method (you must know), they are managed by the controller and generally return 'json'.

The code is naive, intentionally, I didn't want to make a version in 'node.js' or in 'React', 'vue', it is clearly out of the 'hype', I coded it as I work here at home.

Here there are people (lots!) who haven't updated their browsers or their device for more than 10 years and when the sister-in-law who consults the application from a smartphone under Android 3 and with the 1st version from Opera complains that the site does not work, I pass for the last of the losers, already here, working on a computer is not really working...

Thank you for your precious feedback, already some Placido-Shop versions are put into production and the first real payment was made last Friday.
I hope that the struggle with e-commerce software, too slow, too complex and un-hackable, is over.

I suggest you adapt it for your needs but one way to hack it is to offer 2 products instead of 1 ex. Black pants + Red pants, instead of coding a color choice.

I hope I have helped to clarify the operation of the program, again thank you for your valuable feedback.
I will look for the orientation of the images of the products taken from the smartphone - have you tried to orient it differently when taking sight?

**Comment by Raf-sns** [comment]
Hi,
-> "support you by getting the license" 
That's very kind of you but don't worry about that now, you can license it for free by entering:
For the card number only '4242...' then a date in the future and a random 3-digit code.
-> The real payments are not yet set up for the licenses, it will be done at the beginning of the year, when the documentation is finished and when I have a little more feedback from the developers.
